/**
 * PlatformEmitter — writes agent files to platform-specific locations.
 *
 * Supported platforms:
 *   copilot      → .github/agents/{name}.agent.md
 *   cursor       → .cursor/rules/{name}.mdc
 *   claude       → AGENTS.md  (aggregated, one section per agent)
 *   windsurf     → .windsurf/rules/{name}.md
 *   open-plugins → .agents/plugins/agent-framework/agents/{name}.agent.md
 *   opencode     → .opencode/agents/{name}.md
 *
 * The Open Plugins spec (open-plugins.com) defines the canonical layout used by
 * Cursor Directory and other conformant tools.
 *
 * Skills are also emitted to vercel-labs/skills compatible paths so that
 * `npx skills list` and `npx skills update` see them without any extra config:
 *   copilot / cursor / open-plugins → .agents/skills/{name}/SKILL.md
 *   claude                          → .claude/skills/{name}/SKILL.md
 *   windsurf                        → .windsurf/skills/{name}/SKILL.md
 */

import * as path from 'path';
import * as fs from 'fs-extra';
import { Agent, TargetPlatform } from './Agent';

/** Plugin name used for the Open Plugins directory. */
const OPEN_PLUGINS_PLUGIN_NAME = 'agent-framework';

/**
 * Returns the destination file path for a given agent + platform.
 */
export function platformDestPath(
  agent: Agent,
  platform: TargetPlatform,
  projectRoot: string,
): string {
  const name = agent.getMetadata().name;
  switch (platform) {
    case 'copilot':
      return path.join(projectRoot, '.github', 'agents', `${name}.agent.md`);
    case 'cursor':
      return path.join(projectRoot, '.cursor', 'rules', `${name}.mdc`);
    case 'claude':
      return path.join(projectRoot, 'AGENTS.md');
    case 'windsurf':
      return path.join(projectRoot, '.windsurf', 'rules', `${name}.md`);
    case 'open-plugins':
      return path.join(
        projectRoot,
        '.agents',
        'plugins',
        OPEN_PLUGINS_PLUGIN_NAME,
        'agents',
        `${name}.agent.md`,
      );
    case 'opencode':
      return path.join(projectRoot, '.opencode', 'agents', `${name}.md`);
    default:
      return path.join(projectRoot, '.github', 'agents', `${name}.agent.md`);
  }
}

/**
 * Emit agent files for every requested platform.
 * Returns a map of { platform → written file path }.
 */
export async function emitAgent(
  agent: Agent,
  platforms: TargetPlatform[],
  projectRoot: string,
  force = false,
): Promise<Map<TargetPlatform, string>> {
  const written = new Map<TargetPlatform, string>();

  for (const platform of platforms) {
    const dest = platformDestPath(agent, platform, projectRoot);

    if (platform === 'claude') {
      // AGENTS.md is aggregated — handled by emitAgentsClaude()
      continue;
    }

    if (!force && (await fs.pathExists(dest))) {
      continue; // skip existing unless forced
    }

    await fs.ensureDir(path.dirname(dest));
    const content = agent.generateForPlatform(platform);
    await fs.writeFile(dest, content, 'utf-8');
    written.set(platform, dest);
  }

  return written;
}

/**
 * (Re)write AGENTS.md with sections for every provided agent.
 * This replaces the entire file to keep it in sync.
 */
export async function emitAgentsClaude(
  agents: Agent[],
  projectRoot: string,
): Promise<string> {
  const dest = path.join(projectRoot, 'AGENTS.md');

  const header = `# Agents\n\nThis file is auto-generated by agent-framework.\nEdit agent definitions via \`acli install\` / \`acli remove\`.\n\n---\n\n`;
  const sections = agents.map((a) => a.generateClaudeSection()).join('\n---\n\n');

  await fs.writeFile(dest, header + sections, 'utf-8');
  return dest;
}

// ─── Skill Emission (vercel-labs/skills compatible) ─────────────────────────

/**
 * Returns the `npx skills`-compatible destination path for a skill on a given platform.
 *
 * Layout follows https://github.com/vercel-labs/skills#supported-agents:
 *   copilot / cursor / open-plugins → .agents/skills/{name}/SKILL.md
 *   claude                          → .claude/skills/{name}/SKILL.md
 *   windsurf                        → .windsurf/skills/{name}/SKILL.md
 */
export function skillDestPath(
  skillName: string,
  platform: TargetPlatform,
  projectRoot: string,
): string {
  switch (platform) {
    case 'claude':
      return path.join(projectRoot, '.claude', 'skills', skillName, 'SKILL.md');
    case 'windsurf':
      return path.join(projectRoot, '.windsurf', 'skills', skillName, 'SKILL.md');
    case 'copilot':
    case 'cursor':
    case 'open-plugins':
    case 'opencode':
    default:
      // .agents/skills/ is the shared path recognised by Copilot, Cursor, Codex, Amp,
      // OpenCode, Gemini CLI, Replit, Cline, and more (vercel-labs/skills §Supported Agents)
      return path.join(projectRoot, '.agents', 'skills', skillName, 'SKILL.md');
  }
}

/**
 * Write a SKILL.md file to every unique platform-specific skills directory
 * implied by `platforms`.  Deduplication is handled internally so the same
 * `.agents/skills/` path is only written once even if both `copilot` and
 * `cursor` are selected.
 *
 * Returns a list of file paths that were written.
 */
export async function emitSkill(
  skillName: string,
  content: string,
  platforms: TargetPlatform[],
  projectRoot: string,
  force = false,
): Promise<string[]> {
  const written: string[] = [];
  const seen = new Set<string>();

  for (const platform of platforms) {
    const dest = skillDestPath(skillName, platform, projectRoot);
    if (seen.has(dest)) continue;
    seen.add(dest);

    if (!force && (await fs.pathExists(dest))) continue;

    await fs.ensureDir(path.dirname(dest));
    await fs.writeFile(dest, content, 'utf-8');
    written.push(dest);
  }

  return written;
}

// ─── Platform Directory Setup ─────────────────────────────────────────────────

/**
 * Ensure the required directories exist for each platform.
 */
export async function ensurePlatformDirs(
  platforms: TargetPlatform[],
  projectRoot: string,
): Promise<void> {
  const dirsToCreate: string[] = [];

  for (const platform of platforms) {
    switch (platform) {
      case 'copilot':
        dirsToCreate.push(
          path.join(projectRoot, '.github', 'agents'),
          path.join(projectRoot, '.github', 'prompts'),
          path.join(projectRoot, '.github', 'skills'),
          // vercel-labs/skills compatible path (shared with cursor, codex, amp, etc.)
          path.join(projectRoot, '.agents', 'skills'),
        );
        break;
      case 'cursor':
        dirsToCreate.push(
          path.join(projectRoot, '.cursor', 'rules'),
          path.join(projectRoot, '.agents', 'skills'),
        );
        break;
      case 'claude':
        // AGENTS.md at project root — no dir needed for agents
        dirsToCreate.push(path.join(projectRoot, '.claude', 'skills'));
        break;
      case 'windsurf':
        dirsToCreate.push(
          path.join(projectRoot, '.windsurf', 'rules'),
          path.join(projectRoot, '.windsurf', 'skills'),
        );
        break;
      case 'open-plugins':
        dirsToCreate.push(
          path.join(projectRoot, '.agents', 'plugins', OPEN_PLUGINS_PLUGIN_NAME, 'agents'),
          path.join(projectRoot, '.agents', 'plugins', OPEN_PLUGINS_PLUGIN_NAME, 'skills'),
          path.join(projectRoot, '.agents', 'plugins', OPEN_PLUGINS_PLUGIN_NAME, '.plugin'),
        );
        break;
      case 'opencode':
        dirsToCreate.push(
          path.join(projectRoot, '.opencode', 'agents'),
          // OpenCode also reads .agents/skills for shared skills
          path.join(projectRoot, '.agents', 'skills'),
        );
        break;
    }
  }

  for (const dir of dirsToCreate) {
    await fs.ensureDir(dir);
  }
}
