/**
 * PlatformEmitter — writes agent files to platform-specific locations.
 *
 * Supported platforms:
 *   copilot      → .github/agents/{name}.agent.md
 *   cursor       → .cursor/rules/{name}.mdc
 *   claude       → AGENTS.md  (aggregated, one section per agent)
 *   windsurf     → .windsurf/rules/{name}.md
 *   open-plugins → .agents/plugins/agent-framework/agents/{name}.agent.md
 *
 * The Open Plugins spec (open-plugins.com) defines the canonical layout used by
 * Cursor Directory and other conformant tools.
 */

import * as path from 'path';
import * as fs from 'fs-extra';
import { Agent, TargetPlatform } from './Agent';

/** Plugin name used for the Open Plugins directory. */
const OPEN_PLUGINS_PLUGIN_NAME = 'agent-framework';

/**
 * Returns the destination file path for a given agent + platform.
 */
export function platformDestPath(
  agent: Agent,
  platform: TargetPlatform,
  projectRoot: string,
): string {
  const name = agent.getMetadata().name;
  switch (platform) {
    case 'copilot':
      return path.join(projectRoot, '.github', 'agents', `${name}.agent.md`);
    case 'cursor':
      return path.join(projectRoot, '.cursor', 'rules', `${name}.mdc`);
    case 'claude':
      return path.join(projectRoot, 'AGENTS.md');
    case 'windsurf':
      return path.join(projectRoot, '.windsurf', 'rules', `${name}.md`);
    case 'open-plugins':
      return path.join(
        projectRoot,
        '.agents',
        'plugins',
        OPEN_PLUGINS_PLUGIN_NAME,
        'agents',
        `${name}.agent.md`,
      );
    default:
      return path.join(projectRoot, '.github', 'agents', `${name}.agent.md`);
  }
}

/**
 * Emit agent files for every requested platform.
 * Returns a map of { platform → written file path }.
 */
export async function emitAgent(
  agent: Agent,
  platforms: TargetPlatform[],
  projectRoot: string,
  force = false,
): Promise<Map<TargetPlatform, string>> {
  const written = new Map<TargetPlatform, string>();

  for (const platform of platforms) {
    const dest = platformDestPath(agent, platform, projectRoot);

    if (platform === 'claude') {
      // AGENTS.md is aggregated — handled by emitAgentsClaude()
      continue;
    }

    if (!force && (await fs.pathExists(dest))) {
      continue; // skip existing unless forced
    }

    await fs.ensureDir(path.dirname(dest));
    const content = agent.generateForPlatform(platform);
    await fs.writeFile(dest, content, 'utf-8');
    written.set(platform, dest);
  }

  return written;
}

/**
 * (Re)write AGENTS.md with sections for every provided agent.
 * This replaces the entire file to keep it in sync.
 */
export async function emitAgentsClaude(
  agents: Agent[],
  projectRoot: string,
): Promise<string> {
  const dest = path.join(projectRoot, 'AGENTS.md');

  const header = `# Agents\n\nThis file is auto-generated by agent-framework.\nEdit agent definitions via \`acli install\` / \`acli remove\`.\n\n---\n\n`;
  const sections = agents.map((a) => a.generateClaudeSection()).join('\n---\n\n');

  await fs.writeFile(dest, header + sections, 'utf-8');
  return dest;
}

/**
 * Ensure the required directories exist for each platform.
 */
export async function ensurePlatformDirs(
  platforms: TargetPlatform[],
  projectRoot: string,
): Promise<void> {
  const dirsToCreate: string[] = [];

  for (const platform of platforms) {
    switch (platform) {
      case 'copilot':
        dirsToCreate.push(
          path.join(projectRoot, '.github', 'agents'),
          path.join(projectRoot, '.github', 'prompts'),
          path.join(projectRoot, '.github', 'skills'),
        );
        break;
      case 'cursor':
        dirsToCreate.push(path.join(projectRoot, '.cursor', 'rules'));
        break;
      case 'claude':
        // AGENTS.md at project root — no dir needed
        break;
      case 'windsurf':
        dirsToCreate.push(path.join(projectRoot, '.windsurf', 'rules'));
        break;
      case 'open-plugins':
        dirsToCreate.push(
          path.join(projectRoot, '.agents', 'plugins', OPEN_PLUGINS_PLUGIN_NAME, 'agents'),
          path.join(projectRoot, '.agents', 'plugins', OPEN_PLUGINS_PLUGIN_NAME, 'skills'),
          path.join(projectRoot, '.agents', 'plugins', OPEN_PLUGINS_PLUGIN_NAME, '.plugin'),
        );
        break;
    }
  }

  for (const dir of dirsToCreate) {
    await fs.ensureDir(dir);
  }
}
